In [19]:
import numpy as np

x=np.array([[1,2,1,5],[1,5,3,3],[1,1,6,2],[1,7,2,1],[1,3,2,6]]).T
y=np.expand_dims([16,56,18,47],axis=0)
w=np.dot(y,x)
print(w)

[[381 491 274 491 502]]


In [20]:
A,B,C=6,3,4
fe=np.array([[1,-2,2],[1,-1,-3],[1,-2,-3],[1,0,1],[1,2,-1]])
for i in range(5):
    X=fe[i,:]
    d=np.abs(A*X[0]+B*X[1]+C*X[2])/np.sqrt(A**2+B**2+C**2)
    print(d)


1.0242950394631678
1.1523319193960637
1.5364425591947517
1.2803687993289599
1.0242950394631678


In [21]:
print((3.6056/1.0243)**2)

12.390839875035466


In [24]:
x=[9,2,6,1,8]
y=[1,0,3,0,1]
sum=0
for i in range(5):
    sum+=3*x[i]-y[i]
result =2/5 *sum
print(result)

29.200000000000003


In [ ]:
a =0.1
theta =np.zeros(k+1)
e= 0.0001 # a small threshod to stop optimization
while delta_theta > e:
    theta_update  = theta - a*Gradient
    Gradient = sum([gradient[i] for i in range(N)])/N
    delta_theta = theta_update - theta
    theta = theta_update


In [2]:
import numpy as np

def sigmoid(theta,X):
    theta_T=np.transpose(theta)
    N,M=np.shape(X)
    fi_l=[1/(1+np.exp(-theta_T@X[i,:])) for i in range(N)]
    fi=np.array(fi_l)
    return fi


def J(theta,X,Y):
    """
    negative likelihood 
    """
    N,M=np.shape(X)
    fi=sigmoid(theta,X)
    J = sum([-Y[i]*np.log(fi[i])-(1-Y[i])*np.log(1-fi[i]) for i in range(N)])/N
    return J

    
def G_J(theta,X,Y):
    """
    gradient of negative likelihood 
    """
    N,M=np.shape(X)
    fi=sigmoid(theta,X)
    G_l=[]
    for j in range(M):
        G_J_j= sum([(fi[i]-Y[i])*X[i,j] for i in range(N)])/N
        G_l.append(G_J_j)
    G_J=np.array(G_l)
    return G_J

theta=np.array([1.5,2,1])
Y=np.array([0,1,1,0])
X=np.array([[0,0,1],[0,1,0],[0,1,1],[1,0,0]])
print(np.shape(X[1,:]))
mean=np.mean(X,axis=1,keepdims=True)
print(mean)
J=J(theta,X,Y)
G_J = G_J(theta,X,Y)
print(J)
print(G_J)


(3,)
[[0.33333333]
 [0.33333333]
 [0.66666667]
 [0.33333333]]
0.7975475820294224
[ 0.20439362 -0.0416572   0.17090818]


In [27]:
def write_output(output_path,data):
    with open(output_path,'w') as wf:
        wf.write(data) 

data=np.array([[0,0,1],[0,1,0],[0,1,1],[1,0,0]])
write_output('write',str(data))

In [3]:
l=[1,1,1,2]
l.append(1)
print(l)

[1, 1, 1, 2, 1]


In [ ]:
def sigmoid(theta, X):
    # Ensure theta is a column vector
    z = np.dot(X, theta)
    return 1 / (1 + np.exp(-z))

def G_J(theta, X, Y):
    """
    Vectorized gradient of negative log-likelihood.
    """
    N, M = X.shape
    fi = sigmoid(theta, X)
    gradient = np.dot(X.T, (fi - Y)) / N
    return gradient


def predict(theta, X):
    """
    Vectorized prediction function.
    """
    # Compute probabilities using the sigmoid function
    probabilities = sigmoid(theta, X)
    # Convert probabilities to 0 or 1 based on a 0.5 threshold
    return (probabilities >= 0.5).astype(np.int64)


def train(theta, X, Y, num_epoch, learning_rate):
    """
    theta : np.ndarray, shape (D,) where D is feature dimension
    X : np.ndarray, shape (N, D) where N is number of examples
    Y : np.ndarray, shape (N,)
    num_epoch : int, 
    learning_rate : float
    """
    for _ in range(num_epoch):
        gradient = G_J(theta, X, Y)
        theta -= learning_rate * gradient
    return theta

# Example of initialization and training
D = X.shape[1]  # Number of features
theta = np.zeros(D)  # Initialize theta
theta = train(theta, X, Y, num_epoch=100, learning_rate=0.01)



In [12]:
l=[1,1,1,1,1]
a=np.array(l).astype(np.int64)
np.savetxt('try',a,fmt='%d')
print(a)

[1 1 1 1 1]


In [6]:
import numpy as np
x=np.linspace(1000,10000,10)
print(x)

[ 1000.  2000.  3000.  4000.  5000.  6000.  7000.  8000.  9000. 10000.]


In [1]:
from ase.io import read,write
struc=read('15kaw23b_dimer.mol')

struc.calc.get_charges()



RuntimeError: Atoms object has no calculator.

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.exp(arr))
y_init=np.zeros(10)
y=3
y_init[y]=1
y_true=y_init
print(y_true)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [17]:
import numpy as np
a=np.array([0,0,0,0])
b=np.zeros((4,1))
array_1d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
# array_d=array_1d[:,1:]
print(array_1d)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
dic={1:2,3:4,5:6}
new={k:dic[k] for k in list(dic)[:len(dic)]}
print(new)

{1: 2, 3: 4, 5: 6}


In [4]:
str='Mar 21 11:41:51 PM:  INFO: DistributedStructs- Matched with 0 structures'
s_l=str.split(' ')
print(type(int(s_l[9])))


<class 'int'>


In [18]:
import numpy as np 

with open('/Users/dell/Documents/My_research/code/code_class/ML_toolbox/For_10601/HW/en.train_10.twocol.oov','r') as f:
    text=f.read()
sequences = text.strip().split("\n\n")
word_list=[]
tag_list=[]
for i ,seq in enumerate(sequences):
    s_word_list=[]
    s_tag_list=[]
    pair=seq.strip().split('\n')
    for p in pair:
        single_pair=p.strip().split('\t')
        word=single_pair[0]
        tag=single_pair[1]
        s_word_list.append(word)
        s_tag_list.append(tag)
    word_list.append(s_word_list)
    tag_list.append(s_tag_list)

word_list_flatten=[i for sublist in word_list for i in sublist]
tag_list_flatten=[i for sublist in tag_list for i in sublist]

unique_word_arr,index_words=np.unique(np.array(word_list_flatten),return_index=True)
unique_tag_arr,index_tag=np.unique(np.array(tag_list_flatten),return_index=True)

word_dict={k:v for (k,v) in zip(unique_word_arr,index_words)}
tag_dict={k:v for (k,v) in zip(unique_tag_arr,index_tag)}


for seq in word_list:
    word_index_list=[]
    for word in seq:
        index=word_dict[word]
        word_index_list.append(index)
    

for seq in tag_list:
    tag_index_list=[]
    for tag in seq:
        index=tag_dict[tag]
        tag_index_list.append(index)
    









    


    




{'B-LOC': 12, 'B-MISC': 3, 'B-ORG': 1, 'B-PER': 10, 'I-LOC': 688, 'I-MISC': 191, 'I-ORG': 16, 'I-PER': 11, 'O': 0}


In [16]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.autograd import Function
import argparse
from typing import List, Tuple
import time
# import matplotlib.pyplot as plt
import numpy as np
# from metrics import evaluate
# from tqdm import tqdm


class TextDataset(Dataset):
    def __init__(self, train_input: str, word_to_idx: dict, tag_to_idx: dict, idx_to_tag: dict):
        """
        Initialize the dictionaries, sequences, and labels for the dataset

        :param train_input: file name containing sentences and their labels
        :param word_to_idx: dictionary which maps words (str) to indices (int). Should be initialized to {} 
            outside this class so that it can be reused for test data. Will be filled in by this class when training.
        :param tag_to_idx: dictionary which maps tags (str) to indices (int). Should be initialized to {} 
            outside this class so that it can be reused for test data. Will be filled in by this class when training.
        :param idx_to_tag: Inverse dictionary of tag_to_idx, which maps indices (int) to tags (str). Should be initialized to {} 
            outside this class so that it can be reused when evaluating the F1 score of the predictions later on. 
            Will be filled in by this class when training.
        """
        self.sequences = []
        self.labels = []

        i = 0 # index counter for word dict
        j = 0 # index counter for tag dict
        # for all sequences, convert the words/labels to indices using 2 dicts,
        # append these indices to the 2 lists, and add the resulting lists of
        # word/label indices to the accumulated dataset
        with open(train_input, 'r') as f:
            text=f.read()
        sequences = text.strip().split("\n\n")
        word_list=[]
        tag_list=[]
        for i ,seq in enumerate(sequences):
            s_word_list=[]
            s_tag_list=[]
            pair=seq.strip().split('\n')
            for p in pair:
                single_pair=p.strip().split('\t')
                word=single_pair[0]
                tag=single_pair[1]
                s_word_list.append(word)
                s_tag_list.append(tag)
            word_list.append(s_word_list)
            tag_list.append(s_tag_list)

        word_list_flatten=[i for sublist in word_list for i in sublist]
        tag_list_flatten=[i for sublist in tag_list for i in sublist]

        unique_word_arr,index_words=np.unique(np.array(word_list_flatten),return_index=True)
        unique_tag_arr,index_tag=np.unique(np.array(tag_list_flatten),return_index=True)

        word_to_idx={k:v for (k,v) in zip(unique_word_arr,index_words)}
        idx_to_word={v:k for (k,v) in zip(unique_word_arr,index_words)}
        tag_to_idx={k:v for (k,v) in zip(unique_tag_arr,index_tag)}
        idx_to_tag = {v:k for (k,v) in zip(unique_tag_arr,index_tag)}

        self.word_to_idx=word_to_idx
        self.tag_to_idx=tag_to_idx
        self.idx_to_tag = idx_to_tag
        self.idx_to_word = idx_to_word

        for seq in word_list:
            word_index_list=[]
            for word in seq:
                index=word_to_idx[word]
                word_index_list.append(index)
            self.sequences.append(word_index_list)
            

        for seq in tag_list:
            tag_index_list=[]
            for tag in seq:
                index=tag_to_idx[tag]
                tag_index_list.append(index)
            self.labels.append(tag_index_list)
        
        
        
    def __len__(self):
        """
        :return: Length of the text dataset (# of sentences)
        """
        return  len(self.sequences)
        raise NotImplementedError

    def __getitem__(self, idx):
        """
        Return the sequence of words and corresponding labels given input index

        :param idx: integer of the index to access
        :return word_tensor: sequence of words as a tensor
        :return label_tensor: sequence of labels as a tensor
        """
        word_tensor=torch.tensor(self.sequences[idx])
        label_tensor=torch.tensor(self.labels[idx])
        return word_tensor,label_tensor
        raise NotImplementedError

train_input='en.train_10.twocol.oov'
test_input='en.val_10.twocol.oov'
word_to_idx_train={}
tag_to_idx_train={}
idx_to_tag_train={}
word_to_idx_test={}
tag_to_idx_test={}
idx_to_tag_test={}

#load data
training_data=TextDataset(train_input,word_to_idx_train,tag_to_idx_train, idx_to_tag_train)
test_data=TextDataset(test_input,word_to_idx_test,tag_to_idx_test, idx_to_tag_test)
train_dataloader = DataLoader(training_data, batch_size=1, shuffle=False)
test_dataloader = DataLoader(test_data, batch_size=1, shuffle=False)

vocab_size=len(training_data.word_to_idx)
embedding_dim = 10
embeds_se = nn.Embedding(vocab_size, embedding_dim)  
for X,y in train_dataloader:
    print(f'X:{X}')
    sequence_embed = embeds_se(X)
    print(sequence_embed)

X:tensor([[0]])
tensor([[[ 1.7408, -0.8581, -1.0884, -0.4404,  0.6146, -0.3978, -0.2298,
           0.9132, -1.0992,  1.2308]]], grad_fn=<EmbeddingBackward0>)
X:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[[ 3.0011e+00, -1.2253e-01, -9.4884e-01, -8.7381e-01, -2.7630e-01,
          -1.4190e-01, -9.5620e-01,  1.2030e-01,  1.2787e+00,  3.9063e-01],
         [ 2.9716e-01,  9.6621e-02,  1.0501e-01, -1.7138e+00, -9.8092e-01,
          -3.6048e-01,  1.1854e-01, -9.1596e-01,  3.9740e-01, -2.2705e-01],
         [ 8.1950e-01,  1.5035e+00, -1.5939e+00,  1.5770e+00,  1.6330e+00,
           1.2492e+00, -2.5661e-01, -6.0894e-02, -2.9800e-01, -8.3208e-01],
         [ 6.0165e-01,  9.8463e-02,  2.0442e+00,  4.5892e-01, -1.2323e+00,
          -4.3938e-01,  5.2166e-01, -1.3731e+00, -2.2790e-02, -1.5151e+00],
         [-4.0787e-03, -1.7015e+00, -3.5682e-01,  3.7862e-01, -2.2588e+00,
          -4.9085e-01, -5.2506e-01, -3.4265e-01,  1.4004e-03, -7.5565e-02],
         [-3.4336e-01, -3.7470e-01,  1.6693e-0

IndexError: index out of range in self

In [7]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.autograd import Function
import argparse
from typing import List, Tuple
import time
from torch.autograd import gradcheck 



class LinearFunction(Function):
    @staticmethod
    def forward(ctx, input: nn.Parameter, weight: nn.Parameter, bias: nn.Parameter):
        """
        Manual implementation of a Layer Linear forward computation that 
        also caches parameters for the backward computation. 

        :param ctx: context object to store parameters
        :param input: training example tensor of shape (batch_size, in_features)
        :param weight: weight tensor of shape (out_features, in_features)
        :param bias: bias tensor of shape (out_features)
        :return: forward computation output of shape (batch_size, out_features)
        """
        ctx.save_for_backward(input, weight)
        output = (torch.matmul(input, torch.transpose(weight, 0, 1)) 
                                            + bias.reshape((1, weight.shape[0])))
        return output
    
    @staticmethod
    def backward(ctx, grad_output):
        """
        Manual implementation of a Layer Linear backward computation 
        using the cached parameters from forward computation

        :param ctx: context object to access stored parameters
        :param grad_output: partial derviative w.r.t Linear outputs (What is the shape?)
        :returns:
            g_input: partial derivative w.r.t Linear inputs (Same shape as inputs)
            g_weight: partial derivative w.r.t Linear weights (Same shape as weights)
            g_bias: partial derivative w.r.t Linear bias (Same shape as bias, remember that bias is 1-D!!!)
        """
        input, weight = ctx.saved_tensors
        g_input = torch.matmul(grad_output, weight)
        g_weight = torch.matmul(torch.transpose(grad_output, 0, 1), input)
        g_bias = torch.sum(grad_output, dim=0)

        return g_input, g_weight, g_bias

class TanhFunction(Function):
    @staticmethod
    def forward(ctx, input):
        """
        Take the Tanh of input parameter

        :param ctx: context object to store parameters
        :param input: Activiation input (output of previous layers)
        :return: output of tanh activation of shape identical to input
        """
        ctx.save_for_backward(input)
        output= torch.tanh(input)
        return output
        raise NotImplementedError
    
    @staticmethod
    def backward(ctx, grad_output):
        """
        Performs backward computation of Tanh activation

        :param ctx: context object to access stored parameters
        :param grad_output: partial deriviative of loss w.r.t Tanh outputs
        :return: partial deriviative of loss w.r.t Tanh inputs
        """
        input, = ctx.saved_tensors
        grad_input = grad_output * (1 - torch.tanh(input) ** 2)
        return grad_input
        raise NotImplementedError


class ReLUFunction(Function):
    @staticmethod
    def forward(ctx, input):
        """
        Takes the ReLU of input parameter

        :param ctx: context object to store parameters
        :param input: Activation input (output of previous layers) 
        :return: Output of ReLU activation with shape identical to input
        """

        ctx.save_for_backward(input)
        output=torch.relu(input)
        return output
        raise NotImplementedError
    
    @staticmethod
    def backward(ctx, grad_output):
        """
        Performs backward computation of ReLU activation

        :param ctx: context object to access stored parameters
        :param grad_output: partial deriviative of loss w.r.t ReLU output
        :return: partial deriviative of loss w.r.t ReLU input
        """
        input,=ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input <= 0] = 0

        return grad_input
        raise NotImplementedError



# Define or import your custom functions here (LinearFunction, TanhFunction, ReLUFunction)

# Prepare the input tensor
input = torch.tensor([1.7408, -0.8581, -1.0884, -0.4404], dtype=torch.double, requires_grad=True)  # Ensure it's double
input = torch.reshape(input,(2,2))

# Now apply gradcheck
# Note that gradcheck takes the function (passed without ()), and a tuple of inputs
gradcheck_success_tanh = gradcheck(TanhFunction.apply, (input,))
gradcheck_success_relu = gradcheck(ReLUFunction.apply, (input,))

print(f"Gradcheck for TanhFunction: {gradcheck_success_tanh}")
print(f"Gradcheck for ReLUFunction: {gradcheck_success_relu}")


Gradcheck for TanhFunction: True
Gradcheck for ReLUFunction: True
