In [19]:
import numpy as np

x=np.array([[1,2,1,5],[1,5,3,3],[1,1,6,2],[1,7,2,1],[1,3,2,6]]).T
y=np.expand_dims([16,56,18,47],axis=0)
w=np.dot(y,x)
print(w)

[[381 491 274 491 502]]


In [20]:
A,B,C=6,3,4
fe=np.array([[1,-2,2],[1,-1,-3],[1,-2,-3],[1,0,1],[1,2,-1]])
for i in range(5):
    X=fe[i,:]
    d=np.abs(A*X[0]+B*X[1]+C*X[2])/np.sqrt(A**2+B**2+C**2)
    print(d)


1.0242950394631678
1.1523319193960637
1.5364425591947517
1.2803687993289599
1.0242950394631678


In [21]:
print((3.6056/1.0243)**2)

12.390839875035466


In [24]:
x=[9,2,6,1,8]
y=[1,0,3,0,1]
sum=0
for i in range(5):
    sum+=3*x[i]-y[i]
result =2/5 *sum
print(result)

29.200000000000003


In [ ]:
a =0.1
theta =np.zeros(k+1)
e= 0.0001 # a small threshod to stop optimization
while delta_theta > e:
    theta_update  = theta - a*Gradient
    Gradient = sum([gradient[i] for i in range(N)])/N
    delta_theta = theta_update - theta
    theta = theta_update


In [2]:
import numpy as np

def sigmoid(theta,X):
    theta_T=np.transpose(theta)
    N,M=np.shape(X)
    fi_l=[1/(1+np.exp(-theta_T@X[i,:])) for i in range(N)]
    fi=np.array(fi_l)
    return fi


def J(theta,X,Y):
    """
    negative likelihood 
    """
    N,M=np.shape(X)
    fi=sigmoid(theta,X)
    J = sum([-Y[i]*np.log(fi[i])-(1-Y[i])*np.log(1-fi[i]) for i in range(N)])/N
    return J

    
def G_J(theta,X,Y):
    """
    gradient of negative likelihood 
    """
    N,M=np.shape(X)
    fi=sigmoid(theta,X)
    G_l=[]
    for j in range(M):
        G_J_j= sum([(fi[i]-Y[i])*X[i,j] for i in range(N)])/N
        G_l.append(G_J_j)
    G_J=np.array(G_l)
    return G_J

theta=np.array([1.5,2,1])
Y=np.array([0,1,1,0])
X=np.array([[0,0,1],[0,1,0],[0,1,1],[1,0,0]])
print(np.shape(X[1,:]))
mean=np.mean(X,axis=1,keepdims=True)
print(mean)
J=J(theta,X,Y)
G_J = G_J(theta,X,Y)
print(J)
print(G_J)


(3,)
[[0.33333333]
 [0.33333333]
 [0.66666667]
 [0.33333333]]
0.7975475820294224
[ 0.20439362 -0.0416572   0.17090818]


In [27]:
def write_output(output_path,data):
    with open(output_path,'w') as wf:
        wf.write(data) 

data=np.array([[0,0,1],[0,1,0],[0,1,1],[1,0,0]])
write_output('write',str(data))

In [3]:
l=[1,1,1,2]
l.append(1)
print(l)

[1, 1, 1, 2, 1]


In [ ]:
def sigmoid(theta, X):
    # Ensure theta is a column vector
    z = np.dot(X, theta)
    return 1 / (1 + np.exp(-z))

def G_J(theta, X, Y):
    """
    Vectorized gradient of negative log-likelihood.
    """
    N, M = X.shape
    fi = sigmoid(theta, X)
    gradient = np.dot(X.T, (fi - Y)) / N
    return gradient


def predict(theta, X):
    """
    Vectorized prediction function.
    """
    # Compute probabilities using the sigmoid function
    probabilities = sigmoid(theta, X)
    # Convert probabilities to 0 or 1 based on a 0.5 threshold
    return (probabilities >= 0.5).astype(np.int64)


def train(theta, X, Y, num_epoch, learning_rate):
    """
    theta : np.ndarray, shape (D,) where D is feature dimension
    X : np.ndarray, shape (N, D) where N is number of examples
    Y : np.ndarray, shape (N,)
    num_epoch : int, 
    learning_rate : float
    """
    for _ in range(num_epoch):
        gradient = G_J(theta, X, Y)
        theta -= learning_rate * gradient
    return theta

# Example of initialization and training
D = X.shape[1]  # Number of features
theta = np.zeros(D)  # Initialize theta
theta = train(theta, X, Y, num_epoch=100, learning_rate=0.01)



In [12]:
l=[1,1,1,1,1]
a=np.array(l).astype(np.int64)
np.savetxt('try',a,fmt='%d')
print(a)

[1 1 1 1 1]


In [6]:
import numpy as np
x=np.linspace(1000,10000,10)
print(x)

[ 1000.  2000.  3000.  4000.  5000.  6000.  7000.  8000.  9000. 10000.]


In [1]:
from ase.io import read,write
struc=read('15kaw23b_dimer.mol')

struc.calc.get_charges()



RuntimeError: Atoms object has no calculator.

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.exp(arr))
y_init=np.zeros(10)
y=3
y_init[y]=1
y_true=y_init
print(y_true)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [17]:
import numpy as np
a=np.array([0,0,0,0])
b=np.zeros((4,1))
array_1d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
# array_d=array_1d[:,1:]
print(array_1d)


[[1 2 3 4 5]
 [1 2 3 4 5]]
